kind = "api"
previewPath = "/api" # TODO - should be excluded from preview in the first place
title = "API Server"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 8080
name = "API Server"
paths = ["/", "/api", "/uploads"]

[services.development]
run = "pnpm --filter @workspace/api-server run dev"

[services.production]
build = "pnpm --filter @workspace/api-server run build && BASE_PATH=/ pnpm --filter @workspace/ai-dashboard run build"

[services.production.run]
args = ["bash", "scripts/start-production.sh"]

[services.production.run.env]
PORT = "8080"
MODEL_API_PORT = "9878"
NODE_ENV = "production"

[services.production.health.startup]
path = "/api/healthz"
