"""
VideoAgent — AI-driven video production engine.

ALL text content (hook, build, body, drop, cta, outro) is generated by the trained
transformer model using control-token conditioning.  Visual style (colours,
backgrounds, effects, typography) is derived generatively from content DNA —
energy, darkness, warmth, saturation — computed per-video from genre/tone/idea.
No fixed templates are used.
"""
from __future__ import annotations
import re
import math
from dataclasses import dataclass, field
from typing import List, Optional, Dict, Any

from ..model.creative_model import CreativeModel
from ..agents.script_agent import ScriptAgent, ScriptRequest, PLATFORM_CTAS
from ..agents.visual_spec_agent import VisualSpecAgent, VisualSpecRequest, TONE_COLORS
from .cinematic_engine import CinematicRequest, CinematicResult, render_cinematic
from .cinematic_engine import render_cinematic_open
from .renderer import ASPECT_RATIOS, PLATFORM_RATIOS
from .scenes import SceneConfig
from . import ai_scene_builder


# ── Known genre tokens (must match tokenizer.py CONTROL_TOKENS) ─────────────
_KNOWN_GENRE_TOKENS = {
    "trap", "rnb", "r&b", "pop", "afrobeats", "afro", "drill",
    "lofi", "lo_fi", "lo-fi", "indie", "electronic", "soul", "reggaeton",
    "hyperpop", "acoustic", "latin", "jazz", "hiphop", "hip_hop", "hip-hop",
}

_GENRE_TOKEN_MAP: Dict[str, str] = {
    "trap":       "<GENRE_TRAP>",
    "rnb":        "<GENRE_RNB>",
    "r&b":        "<GENRE_RNB>",
    "pop":        "<GENRE_POP>",
    "afrobeats":  "<GENRE_AFROBEATS>",
    "afro":       "<GENRE_AFROBEATS>",
    "drill":      "<GENRE_DRILL>",
    "lofi":       "<GENRE_LOFI>",
    "lo_fi":      "<GENRE_LOFI>",
    "lo-fi":      "<GENRE_LOFI>",
    "indie":      "<GENRE_INDIE>",
    "electronic": "<GENRE_ELECTRONIC>",
    "soul":       "<GENRE_SOUL>",
    "reggaeton":  "<GENRE_REGGAETON>",
    "hyperpop":   "<GENRE_HYPERPOP>",
    "acoustic":   "<GENRE_ACOUSTIC>",
    "latin":      "<GENRE_LATIN>",
    "jazz":       "<GENRE_JAZZ>",
    "hiphop":     "<GENRE_HIPHOP>",
    "hip_hop":    "<GENRE_HIPHOP>",
    "hip-hop":    "<GENRE_HIPHOP>",
}

# Primary: genre determines template.  Tone is a tiebreaker.
_GENRE_TEMPLATE: Dict[str, str] = {
    "trap":        "neon_underground",
    "rnb":         "neo_soul_warmth",
    "r&b":         "neo_soul_warmth",
    "pop":         "neon_pulse",
    "afrobeats":   "afrobeats_vibes",
    "afro":        "afrobeats_vibes",
    "drill":       "drill_streets",
    "lofi":        "lo_fi_chill",
    "lo_fi":       "lo_fi_chill",
    "lo-fi":       "lo_fi_chill",
    "indie":       "indie_aesthetic",
    "electronic":  "techno_industrial",
    "soul":        "vintage_soul",
    "reggaeton":   "reggaeton_energy",
    "hyperpop":    "hyperpop_chaos",
    "acoustic":    "vintage_film",
    "latin":       "reggaeton_energy",
    "jazz":        "vintage_soul",
    "hiphop":      "neon_underground",
    "hip_hop":     "neon_underground",
    "hip-hop":     "neon_underground",
}

# Fallback: tone determines template when genre is absent or unrecognised.
_TONE_TEMPLATE: Dict[str, str] = {
    "edgy":          "dark_cinema",
    "playful":       "neon_pulse",
    "serious":       "dark_academia",
    "energetic":     "music_video",
    "professional":  "elegant_minimal",
    "casual":        "storyteller",
    "promotional":   "cinematic_promo",
    "inspirational": "golden_hour_release",
    "chill":         "lo_fi_chill",
}

# Platform-specific default durations & aspect ratios.
_PLATFORM_SPECS: Dict[str, Dict[str, Any]] = {
    "tiktok":            {"duration": 25.0, "max_dur": 60.0,  "ratio": "9:16"},
    "instagram":         {"duration": 20.0, "max_dur": 60.0,  "ratio": "1:1"},
    "instagram_reels":   {"duration": 30.0, "max_dur": 90.0,  "ratio": "9:16"},
    "instagram_story":   {"duration": 15.0, "max_dur": 15.0,  "ratio": "9:16"},
    "youtube":           {"duration": 60.0, "max_dur": 120.0, "ratio": "16:9"},
    "youtube_shorts":    {"duration": 45.0, "max_dur": 60.0,  "ratio": "9:16"},
    "facebook":          {"duration": 20.0, "max_dur": 60.0,  "ratio": "1:1"},
    "facebook_reels":    {"duration": 30.0, "max_dur": 60.0,  "ratio": "9:16"},
    "twitter":           {"duration": 15.0, "max_dur": 30.0,  "ratio": "16:9"},
    "linkedin":          {"duration": 30.0, "max_dur": 90.0,  "ratio": "16:9"},
    "threads":           {"duration": 20.0, "max_dur": 60.0,  "ratio": "1:1"},
}


def _clean(text: str) -> str:
    text = re.sub(r"<[A-Z_]+>", "", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text


def _is_meaningful(text: str, min_words: int = 2, min_chars: int = 8) -> bool:
    if not text or len(text) < min_chars:
        return False
    words = text.split()
    if len(words) < min_words:
        return False
    ctrl = sum(1 for w in words if w.startswith("<") and w.endswith(">"))
    if ctrl / len(words) > 0.4:
        return False
    if len(set(w.lower() for w in words)) < len(words) * 0.25:
        return False
    return True


# ── Request / Response dataclasses ──────────────────────────────────────────

@dataclass
class VideoAgentRequest:
    idea: str
    platform: str = "tiktok"
    goal: str = "growth"
    tone: str = "energetic"
    genre: str = ""
    artist_name: str = ""
    duration: float = 0.0
    artist_context: Dict[str, Any] = field(default_factory=dict)


@dataclass
class VideoScene:
    scene_type: str
    text: str
    animation: str = "fade"


@dataclass
class VideoProduction:
    platform: str
    aspect_ratio: str
    total_duration: float
    template_id: str
    scenes: List[VideoScene]
    source: str = "ai_model"
    genre_detected: str = ""
    tone_used: str = ""


# ── VideoAgent ──────────────────────────────────────────────────────────────

class VideoAgent:
    """
    Orchestrates the full AI → render pipeline.

    1. Conditions the trained model with platform / goal / tone / genre tokens.
    2. Generates distinct text for every scene in the video.
    3. Selects the matching cinematic template (pure rendering, no text).
    4. Returns a CinematicRequest ready for render_cinematic().
    """

    def __init__(
        self,
        model: CreativeModel,
        script_agent: ScriptAgent,
        visual_spec_agent: VisualSpecAgent,
    ):
        self.model = model
        self.script_agent = script_agent
        self.visual_spec_agent = visual_spec_agent

    # ── Public API ──────────────────────────────────────────────────────────

    def plan(self, req: VideoAgentRequest) -> VideoProduction:
        """Run the AI model to build a full production plan."""
        platform = req.platform.lower().replace(" ", "_")
        tone = req.tone.lower()
        goal = req.goal.lower()
        genre = req.genre.lower().replace(" ", "_")

        specs = _PLATFORM_SPECS.get(platform, _PLATFORM_SPECS["tiktok"])
        if req.duration and req.duration > 0:
            dur = max(6.0, min(req.duration, specs["max_dur"]))
        else:
            dur = specs["duration"]
        ratio = specs["ratio"]

        genre_norm = genre.replace("-", "_").replace(" ", "_")

        # ── Generate all text via the trained model ──────────────────────
        hook  = self._generate_scene_text("hook",  req.idea, platform, tone, goal, genre_norm)
        body  = self._generate_scene_text("body",  req.idea, platform, tone, goal, genre_norm)
        cta   = self._generate_scene_text("cta",   req.idea, platform, tone, goal, genre_norm)

        # For longer formats generate extra scene text driven by model
        build_text = ""
        outro_text = ""
        if dur >= 20.0:
            build_text = self._generate_scene_text("build", req.idea, platform, tone, goal, genre_norm)
        if dur >= 35.0:
            outro_text = self._generate_scene_text("outro", req.idea, platform, tone, goal, genre_norm)

        # ── Fallback: use ScriptAgent as a second-chance AI pass ─────────
        script_source = "ai_model"
        if not (_is_meaningful(hook) and _is_meaningful(body)):
            try:
                sr = self.script_agent.run(ScriptRequest(
                    idea=req.idea, platform=platform, goal=goal, tone=tone
                ))
                if not _is_meaningful(hook):
                    hook = sr.hook
                if not _is_meaningful(body):
                    body = sr.body
                if not _is_meaningful(cta):
                    cta = sr.cta
                script_source = sr.source
            except Exception:
                pass

        if not _is_meaningful(cta):
            cta = PLATFORM_CTAS.get(platform, "Follow for more!")

        # ── Build scene list ─────────────────────────────────────────────
        scenes: List[VideoScene] = []

        if _is_meaningful(hook):
            scenes.append(VideoScene(
                scene_type="hook", text=hook,
                animation=self._pick_animation(tone, "hook")
            ))
        if dur >= 20.0 and _is_meaningful(build_text):
            scenes.append(VideoScene(
                scene_type="build", text=build_text,
                animation=self._pick_animation(tone, "build")
            ))
        if _is_meaningful(body):
            scenes.append(VideoScene(
                scene_type="body", text=body,
                animation=self._pick_animation(tone, "body")
            ))
        if dur >= 35.0 and _is_meaningful(outro_text):
            scenes.append(VideoScene(
                scene_type="outro", text=outro_text,
                animation=self._pick_animation(tone, "outro")
            ))
        if _is_meaningful(cta):
            scenes.append(VideoScene(
                scene_type="cta", text=cta,
                animation=self._pick_animation(tone, "cta")
            ))

        if not scenes:
            scenes = [VideoScene(scene_type="hook", text=req.idea or "New music out now", animation="fade")]

        return VideoProduction(
            platform=platform,
            aspect_ratio=ratio,
            total_duration=dur,
            template_id="ai_derived",
            scenes=scenes,
            source=script_source,
            genre_detected=genre,
            tone_used=tone,
        )

    def build_open_scenes(
        self,
        req: VideoAgentRequest,
        prod: VideoProduction,
        width: int,
        height: int,
    ) -> List[SceneConfig]:
        """
        Convert a VideoProduction into SceneConfig objects via the AI scene
        builder.  No template is involved — visual DNA is computed from
        genre/tone/idea and every parameter is generated fresh.
        """
        scenes_data = [{"type": s.scene_type, "text": s.text} for s in prod.scenes]
        return ai_scene_builder.build_scenes(
            scenes_data=scenes_data,
            idea=req.idea,
            genre=prod.genre_detected,
            tone=prod.tone_used,
            platform=prod.platform,
            artist_name=req.artist_name,
            total_duration=prod.total_duration,
            width=width,
            height=height,
        )

    def render(self, req: VideoAgentRequest) -> CinematicResult:
        """Full pipeline: plan → open scene build → rendered MP4."""
        production = self.plan(req)
        ratio = production.aspect_ratio or PLATFORM_RATIOS.get(production.platform, "9:16")
        width, height = ASPECT_RATIOS.get(ratio, (1080, 1920))
        scene_configs = self.build_open_scenes(req, production, width, height)
        dna = ai_scene_builder.build_dna(req.idea, production.genre_detected, production.tone_used)
        transition = "fadeblack" if dna.darkness > 0.70 else "dissolve" if dna.energy < 0.50 else "fade"
        return render_cinematic_open(
            scenes=scene_configs,
            width=width,
            height=height,
            total_duration=production.total_duration,
            audio_path=req.artist_context.get("audio_path"),
            transition=transition,
            transition_dur=0.5 if dna.energy > 0.70 else 0.8,
            label=f"ai:{production.genre_detected}:{production.tone_used}",
        )

    # ── Internal helpers ────────────────────────────────────────────────────

    def _generate_scene_text(
        self,
        scene_type: str,
        idea: str,
        platform: str,
        tone: str,
        goal: str,
        genre: str,
    ) -> str:
        """
        Call the trained model to generate text for a single scene type.
        Builds a control-token prompt so the model conditions on platform,
        tone, goal, and genre before generating the scene content.
        """
        platform_tok = f"<PLATFORM_{platform.upper()}>"
        tone_tok     = f"<TONE_{tone.upper()}>"
        goal_tok     = f"<GOAL_{goal.upper()}>"
        type_tok     = "<TYPE_VIDEO>"

        genre_key = genre.lower().replace("-", "_").replace(" ", "_")
        genre_tok = _GENRE_TOKEN_MAP.get(genre_key, "")

        stage_map = {
            "hook":  "<STAGE_HOOK>",
            "body":  "<STAGE_BODY>",
            "cta":   "<STAGE_CTA>",
            "build": "<VIDEO_BUILD>",
            "drop":  "<VIDEO_DROP>",
            "outro": "<VIDEO_OUTRO>",
        }
        stage_tok = stage_map.get(scene_type, "<STAGE_BODY>")

        idea_snippet = " ".join(idea.split()[:8]) if idea else ""
        prompt_parts = [type_tok, platform_tok, tone_tok, goal_tok]
        if genre_tok:
            prompt_parts.append(genre_tok)
        prompt_parts.append(stage_tok)
        if idea_snippet:
            prompt_parts.append(idea_snippet)

        prompt = " ".join(prompt_parts)

        try:
            raw = self.model.generate(
                prompt,
                max_new_tokens=70,
                temperature=0.88,
                top_p=0.92,
                top_k=50,
                repetition_penalty=1.2,
            )
            # Strip anything before the stage token (the conditioned prefix)
            if stage_tok in raw:
                raw = raw.split(stage_tok, 1)[-1]
            # Stop at the next stage / video control token
            raw = re.split(r"<(?:STAGE|VIDEO)_[A-Z]+>", raw)[0]
            cleaned = _clean(raw)
            if _is_meaningful(cleaned):
                return cleaned
        except Exception:
            pass

        return ""

    def _select_template(self, tone: str, genre: str) -> str:
        """
        Deterministic mapping: genre beats tone.
        Both are derived from the AI model's generation context.
        """
        g = genre.lower().replace("-", "_").replace(" ", "_")
        if g in _GENRE_TEMPLATE:
            return _GENRE_TEMPLATE[g]
        t = tone.lower()
        return _TONE_TEMPLATE.get(t, "cinematic_promo")

    @staticmethod
    def _pick_animation(tone: str, scene_type: str) -> str:
        """Choose text animation driven by tone and scene position."""
        energetic_tones = {"energetic", "edgy", "playful", "promotional"}
        calm_tones      = {"chill", "serious", "professional", "casual"}

        if scene_type == "hook":
            return "scale_in" if tone in energetic_tones else "slide_up"
        if scene_type in ("build", "drop"):
            return "slide_up"
        if scene_type == "cta":
            return "scale_in" if tone in energetic_tones else "fade"
        return "fade"

    def _build_cinematic_request(
        self,
        req: VideoAgentRequest,
        prod: VideoProduction,
    ) -> CinematicRequest:
        """
        Collapse the multi-scene VideoProduction into a CinematicRequest.
        The cinematic engine's template.build_scenes() maps hook/body/cta
        to its scene layout — we pass the AI-generated text directly.
        """
        texts_by_type: Dict[str, str] = {s.scene_type: s.text for s in prod.scenes}

        hook  = texts_by_type.get("hook", "")
        build = texts_by_type.get("build", "")
        body  = texts_by_type.get("body", "") or build
        cta   = texts_by_type.get("cta", "")

        return CinematicRequest(
            hook=hook,
            body=body,
            cta=cta,
            platform=prod.platform,
            aspect_ratio=prod.aspect_ratio,
            template=prod.template_id,
            duration=prod.total_duration,
            artist_name=req.artist_name,
            quality="cinematic",
            audio_path=req.artist_context.get("audio_path"),
        )
